name       : openttd
version    : 1.11.0
release    : 23
source     :
    - https://cdn.openttd.org/openttd-releases/1.11.0/openttd-1.11.0-source.tar.xz : 5e65184e07368ba1afa62dbb3e35abaee6c4da6730ff4bc9eb4447d53363c7a8
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(lzo2)
    - pkgconfig(sdl2)
setup      : |
    mkdir build && cd build
    %cmake \
        -DCMAKE_INSTALL_BINDIR=bin \
        -DCMAKE_INSTALL_DATADIR=share/openttd \
        -Dshared-dir=share ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    rm -rf $installdir/usr/share/doc/
