name       : openttd
version    : '12.2'
release    : 35
source     :
    - https://cdn.openttd.org/openttd-releases/12.2/openttd-12.2-source.tar.xz : 81508f0de93a0c264b216ef56a05f8381fff7bffa6d010121a21490b4dace95c
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(lzo2)
    - pkgconfig(sdl2)
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_BINDIR=bin \
        -DCMAKE_INSTALL_DATADIR=share/openttd
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/
