name       : openttd
version    : 1.10.3
release    : 21
source     :
    - https://cdn.openttd.org/openttd-releases/1.10.3/openttd-1.10.3-source.tar.xz : c11601ef547eb1f6d4f9a035bd19e0a760b47872ce7d9b4117aaa45ac377b53b
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - lzo-devel
setup      : |
    ./configure \
        --binary-dir=bin \
        --data-dir=share/opentdd \
        --disable-static \
        --install-dir=$installdir \
        --man-dir=man \
        --prefix-dir=/usr \
        --shared-dir=share \
        --with-fontconfig \
        --with-freetype \
        --with-lzma \
        --with-lzo2 \
        --with-png \
        --with-sdl \
        --with-zlib
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc/
