name       : openttd
version    : 1.9.2
release    : 16
source     :
    - https://github.com/OpenTTD/OpenTTD/archive/1.9.2.tar.gz : a2bf71ab3db4c484387c1b3019852f33736e0feb564d5b95625fc81d3843fc06
license    : GPL-2.0
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
    - lzo-devel
setup      : |
    ./configure \
        --binary-dir=bin \
        --data-dir=share/opentdd \
        --disable-static \
        --install-dir=$installdir \
        --man-dir=man \
        --prefix-dir=/usr \
        --shared-dir=share \
        --with-fontconfig \
        --with-freetype \
        --with-lzma \
        --with-lzo2 \
        --with-png \
        --with-sdl \
        --with-zlib
build      : |
    %make
install    : |
    %make_install
