name       : openttd
version    : '13.4'
release    : 37
source     :
    - https://cdn.openttd.org/openttd-releases/13.4/openttd-13.4-source.tar.xz : 2a1deba01bfe58e2188879f450c3fa4f3819271ab49bf348dd66545f040d146f
homepage   : https://www.openttd.org/
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(lzo2)
    - pkgconfig(sdl2)
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_BINDIR=bin \
        -DCMAKE_INSTALL_DATADIR=share/openttd
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/
