name       : openttd
version    : 1.9.1
release    : 15
source     :
    - https://github.com/OpenTTD/OpenTTD/archive/1.9.1.tar.gz : af80c06e98ea8c96f74d188647f9dd04595ae34be92bd28823d4094ce0fc29e7
license    : GPL-2.0
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
    - lzo-devel
setup      : |
    ./configure \
        --binary-dir=bin \
        --data-dir=share/opentdd \
        --disable-static \
        --install-dir=$installdir \
        --man-dir=man \
        --prefix-dir=/usr \
        --shared-dir=share \
        --with-fontconfig \
        --with-freetype \
        --with-lzma \
        --with-lzo2 \
        --with-png \
        --with-sdl \
        --with-zlib
build      : |
    %make
install    : |
    %make_install
