name       : openttd
version    : '12.2'
release    : 33
source     :
    - https://cdn.openttd.org/openttd-releases/12.2/openttd-12.2-source.tar.xz : 81508f0de93a0c264b216ef56a05f8381fff7bffa6d010121a21490b4dace95c
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(lzo2)
    - pkgconfig(sdl2)
setup      : |
    mkdir build && cd build
    %cmake \
        -DCMAKE_INSTALL_BINDIR=bin \
        -DCMAKE_INSTALL_DATADIR=share/openttd \
        -Dshared-dir=share ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    rm -rf $installdir/usr/share/doc/
