name       : openttd
version    : '12.1'
release    : 30
source     :
    - https://cdn.openttd.org/openttd-releases/12.1/openttd-12.1-source.tar.xz : 258bf5b9983010890ba10518b506bc4ab80f7c08ccec59497e9ba55a4aa3e7e3
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(lzo2)
    - pkgconfig(sdl2)
setup      : |
    mkdir build && cd build
    %cmake \
        -DCMAKE_INSTALL_BINDIR=bin \
        -DCMAKE_INSTALL_DATADIR=share/openttd \
        -Dshared-dir=share ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    rm -rf $installdir/usr/share/doc/
